/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bil481;

import java.util.ArrayList;

public class App {
    public static int findNumberOfSearchedElementInTheSameIndex(ArrayList<Integer> list1,ArrayList<Integer> list2, Integer element) 
   {    //If the element we are looking for in two arrays is in the same index, the counter is incremented by one.
        if(list1 == null && list2 == null)
        {
            return 0;
        }
        if(element == null)
        {
            return 0;
        }
        
        int counter = 0;
        int list1Size = list1.size();
        int list2Size = list2.size();
        int small = (list1Size < list2Size ? list1Size : list2Size);
        int element1, element2;
        

        for(int i = 0; i < small; i++)
        {
            element1 = list1.get(i);
            element2 = list2.get(i);
            if(element1 == element && element2 == element)
            {
                counter++;
            }
        }
        return counter;
   }
}
