/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bil481;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test 
    public void testEmptyArrays() {
        ArrayList<Integer> list1 = new ArrayList<>();
        ArrayList<Integer> list2 = new ArrayList<>();
        assertSame(0, App.findNumberOfSearchedElementInTheSameIndex(list1, list2, 5));
    }
    public void testEmptyArray() {
        ArrayList<Integer> list1 = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5));
        ArrayList<Integer> list2 = new ArrayList<>();
        assertSame(0, App.findNumberOfSearchedElementInTheSameIndex(list1, list2, 5));
    }
    @Test 
    public void testFound()
    {
        ArrayList<Integer> list1 = new ArrayList<>(Arrays.asList(1, 5, 3, 4, 5));
        ArrayList<Integer> list2 = new ArrayList<>(Arrays.asList(1, 5, 3, 4, 5));
        assertSame(2, App.findNumberOfSearchedElementInTheSameIndex(list1, list2, 5));
    }
    @Test 
    public void testNotFound()
    {
        ArrayList<Integer> list1 = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5));
        ArrayList<Integer> list2 = new ArrayList<>(Arrays.asList(1, 5, 3, 4, 2));
        assertSame(0, App.findNumberOfSearchedElementInTheSameIndex(list1, list2, 5));
    }
    @Test 
    public void testNullElement()
    {
        ArrayList<Integer> list1 = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5));
        ArrayList<Integer> list2 = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5));
        assertSame(0, App.findNumberOfSearchedElementInTheSameIndex(list1, list2, null));
    }
}
